database:
  # The database initialization SQL script. If not found, the plugin will create a default one.
  init: "init-db.sql"
  
  # The path to the SQLite database file.
  file: "bros_data/bros_data.db"